### ISSUE TITLE
Doesn't work with Pry

### ISSUE THREAD

**Issue by jmuheim** [dblock/guard-rack#14]
It would be nice to use this with `binding.pry`, but though execution is halted on a `binding.pry` breakpoint, it doesn't seem to be possible to interact with Pry and even continue execution: most of the typed input gets ignored, so when e.g. typing `continue`, only something like `ctne` gets recognized by Pry.

**Comment by michaelherold** [comment]
@jmuheim Is this still an issue for you? I am able to use `binding.pry` fine with the current version of `guard-rack`.

**Comment by jmuheim** [comment]
I don't use this gem anymore, so I can't tell. Closing this. Thanks for asking.
