### ISSUE TITLE
Gem broken.

### ISSUE THREAD

**Issue by butcher** [dblock/guard-rack#20]
More info here  https://github.com/dblock/guard-rack/pull/19

**Comment by michaelherold** [comment]
@butcher Can you please confirm that 8d2497e fixes the issue for you?

**Comment by butcher** [comment]
:+1: 
Just check it on `grape-on-rack` with `guard-rack` from master branch. Works great! Thank you @michaelherold for the fast fix.

**Comment by michaelherold** [comment]
Sorry for the bad release! I'm glad I was able to quickly fix it for you.

I'll release 2.1.1 here in a moment and add that suggestion to the releasing process. Thank you for the report.
